### ISSUE TITLE
Support checkbox/radio/textarea/select

### ISSUE THREAD

**Issue by kentcdodds** [brophdawg11/remix-validity-state#15]
I've got use cases for each of these :)

**Comment by kentcdodds** [comment]
Something I just noticed is that for checkboxes, the value that's posted when the checkbox is checked is "on", if it's not checked, it doesn't even appear. Would be cool if the typings showed that.

**Comment by brophdawg11** [comment]
Got _something_ started on this - radio/checkbox oughta be interesting to track down the nuanced differences from text inputs 😀

**Comment by brophdawg11** [comment]
Released in `0.8.0`
