### ISSUE TITLE
Date range validation

### ISSUE THREAD

**Issue by kentcdodds** [brophdawg11/remix-validity-state#21]
I'm building a date range picker with two date inputs and I'd like to validate that the end date does not come before the start date and the start is not after the end. It would be cool if I could somehow dynamically set the `min` and `max` based on other fields in the form or even have some way to set that via `useValidatedInput`/`Field`/etc. so I can control the state myself with whatever I need and just pass what those validation values should be dynamically.

**Comment by brophdawg11** [comment]
I assume, you specifically want to do this using the built-in `min` and `max` I assume?

🤔 what would that API look like - we already support functions in `formValidations` for custom validations.  Maybe if you provide a function for a known HTML validation attribute we let you define the value based on current `formData` rather than treating it as a custom validation function?

```
let formValidations = {
  startDate: {
    required: true,
    max(formData) {
      // Returning undefined would leave this validation attribute off the input entirely
      return formData.get('endDate') || undefined
    }
}
```

---

FWIW, I think you probably realize this but I _think_ now that we're passing `formData` into the custom validations on the server side (merged, but not released to npm)- you should be able to do this with custom validations (but I agree doing it with the built-in's is better):

```jsx
let formValidations = {
  startDate: {
    beforeEndDate(value, formData) {
      return formData.get('endDate') == null || 
        dateIsBefore(value, formData.get('endDate')
    },
  endDate: {
    afterStartDate(value, formData) {
      return formData.get('startDate') == null || 
        dateIsBefore(value, formData.get('startDate')
    }
  },
};
```

This underlying issue is related to the discussion in https://github.com/brophdawg11/remix-validity-state/issues/10#issuecomment-1241987108 - used to have a nice and easy solve for that in SPA's 😄

**Comment by kentcdodds** [comment]
Yup. Got a workaround for now. But yeah I think it would be cool if there were some way to dynamically set the value of a built-in validation. Maybe if you make a built-in validation a function it should return what the attribute value should be? Seems like it may be sensible to separate built-in validations from custom ones:

```ts
let formValidations = {
  startDate: {
    type: 'date',
    required: true,
  },
  endDate: {
    type: 'date',
    required: true,
    min(value, formData) {
      // return the value you want set for this attribute
      return dateFns.format(
        dateFns.parseISO(formData.get('startDate')),
        'yyyy-MM-dd',
      )
    },
    custom: {
      myCustomThing: () => {
        // whatever I need
      },
    },
  },
}
```

In fact, "validations" does not seem necessarily the right name for this object. It really should be "formElements". So then `custom` could be `customValidators`.

This is starting to give me sold angular-formly vibes :) http://angular-formly.com

**Comment by brophdawg11** [comment]
I played with this a bit and yeah the types are getting a little nasty trying to support it as a flat structure now that we have so many potential key/value combinations:

```
validations = {
  // built in with a boolean value
  required: true,
  // built in with a string value
  pattern: '/.../',
  // built in with a number value
  minlength: 5,
  // built in with a dynamic value returning a string
  min: (formData) => { ... },
  // custom validation returning a boolean isValid
  emailAddress: (value) => boolean
}
```

I think I'm going to take a stab at a combination of https://github.com/brophdawg11/remix-validity-state/pull/17#discussion_r987157317 and your suggestion above and try a more verbose (+ clearer and more easily statically typed) structure.  Maybe something like the following (bikeshedding welcome 😉 ):

```
let formInfo = {
  inputs: {
    emailAddress: {
      validationAttrs: {
        type: 'email',  
        // static attribute value
        required: true,
        // dynamically generated attribute value
        minLength(formData) { ... }, 
      },
      customValidations: {
        // custom validations are always a function
        isUniqueEmail(value, formData) { ... },
      },
      errorMessages: {
        // optional field-specific custom error messages
        isUniqueEmail(attrValue, name, value) { ... },
      }
    },
  },
  // global form level custom error messages
  errorMessages: {
    required(attrValue, name, value) { ... }
  }
}
```

Schema-driven forms aren't a primary goal but also something I figured I'd add eventually.  This could also open up the ability to add like an `order` field or something to specify ordering if I didn't want to use a separate array.

Hope to find a chunk of time this weekend to look into this 👍

**Comment by kentcdodds** [comment]
Feel free to ignore this, but when I was maintaining angular-formly, I got several folks asking for https://json-schema.org/ support. I couldn't do it because I was too far down the road, but something to think about at this early stage maybe.

**Comment by brophdawg11** [comment]
@kentcdodds that's an interesting idea, I moved that over to https://github.com/brophdawg11/remix-validity-state/discussions/24 to think through it in some more detail 👍

**Comment by MichaelDeBoey** [comment]
@brophdawg11 Would love to have this for `number` fields as well

For instance: I have 2 inputs 'min' & 'max', where I want to make sure the 'max' field is never less than the 'min' field & the `min` field is never higher than the `max` field

**Comment by brophdawg11** [comment]
@MichaelDeBoey yeah this API should handle any type of dependent validation like that since the plan is to hand the full `formData` to you if you provide a `function` for the attribute instead of a `string`.  Using the new structure from #26 I think it'll look something like:

```js
let formDefinition = {
  inputs: {
    low: {
      validationAttrs: {
        type: 'number',
        // low field can never be higher than high.  If high has no value this 
        // returns undefined so we will not render the validation attribute
        max: formData => formData.get('high')        
      }
    },
    high: {
      validationAttrs: {
        type: 'number',
        // high field can never be lower than low
        min: formData => formData.get('low')
      }
    },
  }
}
```
