### ISSUE TITLE
Compose refs

### ISSUE THREAD

**Issue by kentcdodds** [brophdawg11/remix-validity-state#4]
So I can specify my own. Similar to what we do in downshift here: https://github.com/downshift-js/downshift/blob/10542494cbb42f27e61234de831de20a606940a4/src/downshift.js#L495 https://github.com/downshift-js/downshift/blob/10542494cbb42f27e61234de831de20a606940a4/src/utils.js#L107-L117

**Comment by brophdawg11** [comment]
Just released this in `0.6.0` 👍

**Comment by kentcdodds** [comment]
Thanks!
