### ISSUE TITLE
Consider allowing controlled inputs—example of problem with HeadlessUI Listbox

### ISSUE THREAD

**Issue by CSFlorin** [brophdawg11/remix-validity-state#45]
I realize you said you don't want to go this way, but I'm trying to use this with [HeadlessUI Listbox](https://headlessui.com/react/listbox#using-as-an-uncontrolled-component) but their component has some issues that prevent it from being used uncontrolled in a form: 

1. It doesn't trigger the form's onChange, meaning the value you expose is not updated. I filed an issue a couple weeks ago there for another component (but Listbox also seems to exhibit it) along with an idea of the solution but no word yet https://github.com/tailwindlabs/headlessui/issues/2180
2. When uncontrolled, they use a hidden input to track the value in the DOM, but something is causing the inputEl.form to not be available—maybe they are not forwarding the ref—and this library errors.
3. The field's onChange is a callback with just the value, not the full event like this library might expect from a native element.

Therefore, Listbox is only usable as a controlled input when used in a HTML form.

Here is [a minimal repro](https://stackblitz.com/edit/github-mvq4kg?file=app%2Froutes%2Findex.tsx&title=remix-validity-state%20Demo%20App). Keep in mind we use an InputDefinition because the Listbox doesn't render a proper select; it just renders a hidden input whose value is kept in sync with the component.

It's common for UI library inputs to not work uncontrolled, so other form validation libraries like React Hook Form provide a way to work with controlled inputs. RHF says "React Hook Form embraces uncontrolled components and native inputs, however it's hard to avoid working with external controlled component such as [React-Select](https://github.com/JedWatson/react-select), [AntD](https://github.com/ant-design/ant-design) and [MUI](https://mui.com/). This wrapper component will make it easier for you to work with them."

**Comment by brophdawg11** [comment]
This seems like an issue that needs to be addressed by Headless UI, or maybe it's just not a good fit with this library.  The entire goal of this library is to use native HTML inputs and native HTML validation, so I'm not surprised that it doesn't play nice with a UI library that tries to completely hide the native inputs from you.  

Generally speaking, `remix-validity-state` can play nicely with any library in which you have access to the rendered input, so you can pass along `getInputAttrs`.  If you do not have access to the actual input DOM node, then the best option at the moment would be to proxy changes from the controlled input to a hidden DOM input you _do_ have access to and then you can use that input normally: https://stackblitz.com/edit/github-mvq4kg-onn1wx?file=app%2Froutes%2Findex.tsx
