### ISSUE TITLE
Better TypeScript types on validation attributes

### ISSUE THREAD

**Issue by andrecasal** [brophdawg11/remix-validity-state#50]
TypeScript isn't happy with this:
```tsx
type FormValidations = {
	inputs: {
		email: InputDefinition
	}
}

const formValidations: FormValidations = {
	inputs: {
		email: {
			validationAttrs: {
				type: 'email',
				required: true,
				minLength: min_email_length
			}
		}
	}
}

const Login = () => {
	return (
		<StyledForm method="post">
			<div>
				<label>Email<input {...formValidations.inputs.email.validationAttrs} /></label>
			</div>
			<Button type="submit" action="primary">Login</Button>
		</StyledForm>
	)
}
```
I'm getting this error on any validation attribute:
```
Types of property 'maxLength' are incompatible.
Type 'number | BuiltInValidationAttrsFunction<number>' is not assignable to type 'number | undefined'.
Type 'BuiltInValidationAttrsFunction<number>' is not assignable to type 'number'.
```

But this fixes it:
```diff
-declare type BuiltInValidationAttrsFunction<T> = (fd: FormData) => T | null | undefined;
interface BuiltInValidationAttrs {
-    type?: string | BuiltInValidationAttrsFunction<string>;
-    required?: boolean | BuiltInValidationAttrsFunction<boolean>;
-    minLength?: number | BuiltInValidationAttrsFunction<number>;
-    maxLength?: number | BuiltInValidationAttrsFunction<number>;
-    min?: number | BuiltInValidationAttrsFunction<number>;
-    max?: number | BuiltInValidationAttrsFunction<number>;
-    pattern?: string | BuiltInValidationAttrsFunction<string>;
+    type?: string;
+    required?: boolean;
+    minLength?: number;
+    maxLength?: number;
+    min?: number;
+    max?: number;
+    pattern?: string;
}
```

The optional property operator `?` is already there making it possibly undefined.

What is the `BuiltInValidationAttrsFunction<T>` helping with?

**Comment by brophdawg11** [comment]
What is the type of `min_email_length`?  I don't see any TS issues if I define it as `number | undefined`:

```ts
type FormValidations = {
	inputs: {
		email: InputDefinition
	}
}

const min_email_length: number | undefined = 10;

const formDefinition: FormValidations = {
	inputs: {
		email: {
			validationAttrs: {
				type: 'email',
				required: true,
				minLength: min_email_length
			}
		}
	}
}
```

The `BuiltInValidationAttrsFunction<T>` allows you to define validation attributes values dependent on other form field values - see https://github.com/brophdawg11/remix-validity-state/pull/29.

**Comment by andrecasal** [comment]
Ah got it!

`min_email_length` is `number`. I changed it to `minLength: 4` but the error remains the same. Using the latest v0.10.0.

Should I make a repo to demo it?

**Comment by brophdawg11** [comment]
🤔 Yeah that would help if I can't reproduce it locally.  Thanks!

**Comment by andrecasal** [comment]
[Here's](https://github.com/andrecasal/remix-full-stack-validation) a reproduction of the issue.

**Comment by brophdawg11** [comment]
Ah ok.  Sorry it wasn't clear to me that your error was happening in the JSX not the form definition.  This error is because you're spreading the `formDefinition` `validationAttrs` onto the `<input>` directly instead of using `useValidatedInput`/`getInputAttrs` as follows:

```jsx
const Index = () => {
  const actionData = useActionData<ActionData>();
  let { getInputAttrs } = useValidatedInput({
    formDefinition: formValidations,
    name: "email",
  });
  return (
    <Form method="post">
      <input {...getInputAttrs()} />
      <button type="submit">Submit</button>
      <p>Email: {actionData?.fields?.email}</p>
    </Form>
  );
};
```

In order to support dynamic validation attribute values the definition has to accept both `number` _or_  a function returning a `number`.  `useValidatedInput`/`getInputAttrs` is then what executes the function if needed and results in a narrowed `number` value for `minLength`.

**Comment by andrecasal** [comment]
Ah, I got confused with the documentation, got it, thanks!
