### ISSUE TITLE
Feature Request: Form checkValidity method

### ISSUE THREAD

**Issue by eljaim** [brophdawg11/remix-validity-state#55]
It would be super helpful to have something just like the form's native checkValidity method https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/checkValidity but that includes custom validity checks. This would make it so we don't have to do something like 

```
Boolean(
  Object.entries({
    ...nameInput.info.errorMessages,
    ...addressInput.info.errorMessages,
    ...
  }).length
)
```

if we want to check if the entire form is valid to, for example, disable the submit button until everything is valid.

**Comment by brophdawg11** [comment]
Agreed!  I've got this idea captured in https://github.com/brophdawg11/remix-validity-state/issues/35 so I'm going to close this out in favor of that 👍
